################################################################################
#                     ____  _        ____  _   _   ____                        #
#                    / ___|| | _____|  _ \| | | | |___ \                       #
#                    \___ \| |/ / _ \ |_) | | | |   __) |                      #
#                     ___) |   <  __/  __/| |_| |  / __/                       #
#                    |____/|_|\_\___|_|    \___/  |_____|                      #
#                                                                              #
#                        ~ SkePU 2 options Makefile ~                          #
################################################################################

# NOTE:
# Override the variables set in Makefile here.
# DO NOT PUSH MODIFICATIONS TO THIS FILE UPSTREAM unless absolutely neccessary.

LLVM_BIN = ~/Developer/Repos/build/bin
CLANG_SRC = ~/Developer/Repos/Clang
SKEPU_SRC = ../../..

CXX = g++-6
OPENCL_FLAGS = -framework OpenCL

CLANGTOOL_USER_FLAGS  = -I /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/
CLANGTOOL_USER_FLAGS += -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/
